shopproject/cartapp/urls.py
from django.urls import path
from . import views

app_name = 'cart_app'
urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_details, name='cart_details'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('delete/<int:product_id>/', views.deletion, name='deletion'),
]

shopproject/searchapp/urls.py
from django.urls import path
from . import views

app_name = 'search_app'
urlpatterns=[
    path('',views.search,name='search'),
    ]

shopproject/shopapp/urls.py
from . import views
from django.urls import path

app_name = 'shopapp'

urlpatterns = [
    path('', views.allProdCat, name='all_products'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:pro_slug>/', views.proDetail, name='product_category_details'),

]

shopproject/shopproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shopapp/', include('shopapp.urls')),
    path('search',include('searchapp.urls')),
    path('cart/',include('cartapp.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

shopproject/cartapp/models.py
from django.db import models
from shopapp.models import Products


class Cart(models.Model):
    Cart_id = models.CharField(max_length=250, null=True)
    Date_Added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['Date_Added']

    def __str__(self):
        return '{}'. format(self.Cart_id)


class Cart_Item(models.Model):
    Product = models.ForeignKey(Products, on_delete=models.CASCADE)
    Cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    Quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'Cart_Item'

    def Sub_Total(self):
        return self.Product.price * self.Quantity

    def __str__(self):
        return '{}' .format(self.Product)

shopproject/searchapp/models.py
from django.db import models

# Create your models here.

shopproject/shopapp/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shopapp:products_by_category', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Products(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='products', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    def get_url(self):
        return reverse('shopapp:product_category_details', args=[self.category.slug,self.slug])

    def __str__(self):
        return '{}'.format(self.name)

shopproject/cartapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.shortcuts import HttpResponse
from shopapp.models import Category,Products
from .models import Cart,Cart_Item
from django.core.exceptions import ObjectDoesNotExist


# Create
def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
        return cart


def add_cart(request, product_id):
    product = Products.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(Cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            Cart_id=_cart_id(request)
        )
        cart.save()
    try:
        cartitem = Cart_Item.objects.get(Product=product, Cart=cart)
        if cartitem.Quantity < cartitem.Product.stock:
            cartitem.Quantity += 1
        cartitem.save()
    except Cart_Item.DoesNotExist:
        cartitem = Cart_Item.objects.create(
            Product=product,
            Quantity=1,
            Cart=cart
        )
        cartitem.save()
    return redirect('cart_app:cart_details')


def cart_details(request, total=0, counter=0, cartitem=None):
    try:
        cart = Cart.objects.get(Cart_id=_cart_id(request))
        cartitem = Cart_Item.objects.filter(Cart=cart, active=True)
        for car in cartitem:
            total += (car.Product.price * car.Quantity)
            counter += car.Quantity
    except ObjectDoesNotExist:
        pass
    return render(request, 'cart.html', dict(cartitems=cartitem, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(Cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = Cart_Item.objects.get(Product=product, Cart=cart)
    if cart_item.Quantity > 1:
        cart_item.Quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart_app:cart_details')


def deletion(request, product_id):
    cart = Cart.objects.get(Cart_id=_cart_id(request))
    product = get_object_or_404(Products, id=product_id)
    cart_item = Cart_Item.objects.get(Product=product, Cart=cart)
    cart_item.delete()
    return redirect('cart_app:cart_details')

shopproject/searchapp/views.py
from django.shortcuts import render
from shopapp.models import Products
from django.db.models import Q


# Create your views here.
def search(request):
    products = None
    query = None

    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Products.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'searchpage.html', {'query': query, 'products': products})

shopproject/shopapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Products, Category
from django.core.paginator import Paginator, EmptyPage, InvalidPage


# Create your views here.
def allProdCat(request, c_slug=None):
    c_page = None
    products_list = None
    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Products.objects.all().filter(category=c_page, available=True)
    else:
        products_list = Products.objects.all().filter(available=True)
    new = Paginator(products_list, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = new.page(page)
    except(EmptyPage, InvalidPage):
        products = new.page(new.num_pages)

    return render(request, "category.html", {'cat': c_page, 'pro': products})


def proDetail(request, c_slug, pro_slug):
    try:
        prodet = Products.objects.get(category__slug=c_slug, slug=pro_slug)
    except  Exception as e:
        raise e
    return render(request, 'prodetail.html', {'product': prodet})

shopproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <script src="https://kit.fontawesome.com/fc51e437b8.js" crossorigin="anonymous"></script>
    <meta name="description"> {% block metadescription %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
{% include 'header.html' %}

{% include 'nav.html' %}
{% block content %}
{% endblock %}
 </div>
{% include 'footer.html' %}
<!--<script src="{% static 'js/popper.min.js' %}"></script>-->
<!--<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

shopproject/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}

{% block title %}
     Cart - abc company.pvt.ltd
{% endblock %}

{% block content %}
{% if not  cartitems %}
<div>
    <div class="text-center">
        <br>
           <h1 class="text-center my_title">
                your cart is empty
           </h1>
              <p class="text-center">
                   pleace click <a href="{% url 'shopapp:all_products' %}">here</a>to continue shopping
              </p>
    </div>
</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your Shopping Cart
        </h1>
        <br>
    </div>

    <div class="row mx-auto">
        <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
            <table class="table my_table">
                <thead class="my_table_head">
                <tr>
                    <th colspan="5">
                        <div class="text-center ">Your Items </div>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for pro_cart in cartitems %}
                <tr>
                    <td>
                        <a href="pro_cart.Product.get_absolute_url"><img src="{{pro_cart.Product.image.url}}" style="width:200px;height:200px" class="float-left rounded custom-image"></a>
                    </td>

                    <td class="text-left">
                        {{pro_cart.Product.name}}
                        <br>
                        sku: {{pro_cart.Product.id}}
                        <br>
                        Actual Price: ${{pro_cart.Product.price}}
                        <br>
                        Quantity: {{pro_cart.Quantity}} x $
                    </td>

                    <td>
                        $ {{pro_cart.sub_total}}
                    </td>
                    {% if pro_cart in Quantity < pro_cart.Product.stock %}
                    <td>
                        <a href="{% url 'cart_app:add_cart' pro_cart.Product.id %}" class="custom_a"> <i class="fa fa-plus custom_icon"> </i></a>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' pro_cart.Product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:deletion' pro_cart.Product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>

                    </td>
                    {% else %}
                     <td>
                        &nbsp;<a href="{% url 'cart_app:cart_remove' pro_cart.Product.id %}" class="custom_a"> <i class="fa fa-minus custom_icon"></i></a>
                        &nbsp;<a href="{% url 'cart_app:deletion' pro_cart.Product.id %}" class="custom_icon"> <i class="fa fa-trash custom_icon"></i></a>
                     </td>
                </tr>
                    {% endif %}
                </tbody>
                {% endfor %}
            </table>
        </div>

          <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
             <table class="table my_table">
                 <thead class="my_table_head">
                   <tr>
                      <th>
                        <div class="text-center"> CheckOut </div>
                      </th>
                   </tr>
                 </thead>
                    <tbody>
                      <tr>
                         <td style="color:blue;" class="text-center">
                           <marquee>pleace review your shopping cart item before proceeding with the order payment</marquee>
                         </td>
                      </tr>
                    </tbody>
                      <td class="text-left">
                          Your Total Is : <strong> {{ total }} </strong>
                      </td>
             </table>
              <div class="mx-auto">
                 <center>  <a href="{% url 'shopapp:all_products' %}" class="btn btn-secondary  btn-block my_table_button" style="width:200px">Continue Shopping</a>
                     <a href="{% url 'shopapp:all_products' %}" class= "btn btn-info   btn-block my_table_button" style="width:200px">Payment</a></center>

              </div>
    </div>
{% endif %}
    </div>
</div>
{% endblock %}

shopproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

    {% if cat %}
        {{cat.description|truncatewords:150}}
    {% endif %}
{% endblock %}

{% block title %}
    {% if cat %}
       {{cat.name}}
    {% else %}
      <h4>hello welcome to our store</h4>
    {% endif %}
{% endblock %}

{% block content %}
{% if cat %}
<div>
     <div class="row my_row_class">
         <div class="mx_auto">
         <p><a href="{% url 'shopapp:all_products' %}">our product collections</a></p>
         </div>
     </div>
    <div class="mx_auto">
        <img class="my_image" src="{{cat.image.url}}">
    </div>
 </div>
{% endif %}
<div class="mx_auto">
    {% if cat %}
    <img class="my_image" src="{{cat.image.url}}" style="width:250px;height:250px" alt="{{cat.name}}">
</div>
   <br>
<div>
    <h1 class="text-center my_title">{{cat.name}}</h1>
    <p class="text-justify">{{cat.description}}</p>
    </div>
    {% else %}
        <div>
            <img class="my_image my_image_padding" src="{% static 'img/banner.jpg' %}" width="200px" height="200px" alt="product banner">
        </div>
         <br>




        <div>
            <h1 class="text-center my_title">our products here</h1>
            <p class="text-justify">Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur, from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source</p>

        </div>
    {% endif %}

<div class="container">
    <div class="row mx-auto">
        {% for product in pro.object_list %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" style="width:250px;height:250px" src="{{product.image.url}}" width="250" height="250px" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx_auto">
        {% if pro.paginator.num_pages > 1 %}
        <hr>
    <div class="text-center">
        {% for pg in pro.paginator.page_range %}
           <a href="?page={{pg}}"
              class="btn btn-success btn-sm {% if pro.number == pg %} active {% endif %}">{{pg}}</a>
        {% endfor %}
    </div>
     {% endif %}
        </div>
    <br>

</div>

{% endblock %}

shopproject/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
    <p class="text-center">&copy; all rights are reserved</p>
</div>

shopproject/templates/header.html
{% load static %}
<header>
  <center>
    <a href="{% url 'shopapp:all_products' %}"></a> <img src="{% static 'img/logo.png' %}" width="200px" height="200px" alt="logoimage">
    </center>
</header>

shopproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
        <a class="nav-link" href="#">Home</a>
      </li>
      <li class="nav-item dropdown {% if 'shopapp' in request.path %} active {% endif %}">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" href="{% url 'shopapp:all_products' %}"></a>all products</li>
          {% for new in links %}
          <li><a class="dropdown-item" href="{{new.get_url}}">{{new.name}}</a></li>
             {% endfor %}
        </ul>
      </li>
      {% if item_count > 0 %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'cart_app:cart_details' %}"><i class="fa-solid fa-cart-flatbed-suitcase"></i>({{item_count}})</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:search' %}" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" name="q" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"> <i class="fa fa-search"></i></button>
    </form>
  </div>
</nav>

shopproject/templates/prodetail.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}

{% endblock %}


{% block title %}
    {% if cat %}
       {{product.name}}

    {% endif %}
{% endblock %}

{% block content %}
<div class="row my_prod_row_class">
    <div class="mx_auto">
        <p> <a href="{% url 'shopapp:all_products' %}">HOME</a> | <a href="{{product.category.get_url}}">{{product.category}}</a> | {{product.name}} </p>
    </div>
</div>
<div class="container">
<br>
<div class="row">
    <div class="col-12 col-sm-12 col-md-12 col-lg-6 text-center">
        <div style="min-width:18rem">
            <img src="{{product.image.url}}" alt="{{product.name}}" style="width:200px;height:200px">
        </div>
    </div>

        <div class="col-12 col-sm-12-col-md-12 col-lg-6">
            <div>
            <h6 class="my_prod_name">{{product.name}}</h6>
            <p>${{product.price}}</p>
            <p class="my_title">Product Description</p>
            <p class="text-justify my_prod_text">{{product.description}}</p>
            {% if product.stock <= 0 %}
               <p class="text-justify my_prod_text"><b>out of stock</b></p>
            {% else %}
             <a class="btn btn-success" href="{% url 'cart_app:add_cart' product.id %}">Add To Cart</a>
            {% endif %}

        </div>
            </div>
    </div>
</div>

{% endblock %}

shopproject/templates/searchpage.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
     we have variety of products.
{% endblock %}

{% block title %}
     search
{% endblock %}

{% block content %}
   <div>
       <p class="text-center search_page_text">you have searched for:<b>"{{query}}"</b></p>
   </div>

<div class="container">
    <div class="row mx-auto">
        {% for product in products %}
        <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-lg-4">
            <div class="card text-center" style="min-width:18rem;">
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" width="250px" height="250px" alt="{{product.name}}"></a>
                <div class="card-body">
                    <h3>{{product.name}}</h3>
                    <p>{{product.price}}</p>
                </div>
            </div>
        </div>
        {% empty %}
        <div class="row mx-auto">
          <p class="text-center search_page_text">0 results found</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}